apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
        - command:
            - /manager
          env:
            - name: MATRIX_CONFIG_CONTENT
              valueFrom:
                configMapKeyRef:
                  name: compat-matrix-config
                  key: versionConfigContent
                  optional: true
            - name: MATRIX_CONFIG_URL
              valueFrom:
                configMapKeyRef:
                  name: compat-matrix-config
                  key: versionConfigURL
                  optional: true
            - name: VDO_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: AUTO_UPGRADE
              valueFrom:
                configMapKeyRef:
                  name: compat-matrix-config
                  key: auto-upgrade
          args:
            - --leader-elect
            - --logtostderr
          image: controller:latest
          name: manager
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /etc/kubernetes
              name: vsphere-config-volume
          securityContext:
            allowPrivilegeEscalation: false
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 20Mi
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
      volumes:
        - hostPath:
            path: /etc/kubernetes
            type: DirectoryOrCreate
          name: vsphere-config-volume
